export const environment = {
  production: true,
  AppName: 'Booky',
  RefreshError: 'REFRESH_EXPIRE',
  Months: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  StateColors: [
    '#D9CC53',
    '#698495',
    '#418DE4',
    '#88C956',
    '#9056C9',
    '#56C9BD',
    '#D95381',
  ],
};
